import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import rateLimit from 'express-rate-limit';
import { authRouter } from './routes/auth';
import { shopRouter } from './routes/shop';
import { customersRouter } from './routes/customers';
import { framesRouter } from './routes/frames';
import { lensesRouter } from './routes/lenses';
import { accessoriesRouter } from './routes/accessories';
import { ordersRouter } from './routes/orders';
import { labOrdersRouter } from './routes/labOrders';
import { repairsRouter } from './routes/repairs';
import { prescriptionsRouter } from './routes/prescriptions';
import { staffRouter } from './routes/staff';
import { invoicesRouter } from './routes/invoices';
import { reportsRouter } from './routes/reports';
import { errorHandler } from './middleware/errorHandler';
const app = express();
const PORT = parseInt(process.env.PORT || '4000', 10);
app.set('trust proxy', 1);
app.use(helmet());
app.use(cors({ origin: (_o: any, cb: any) => cb(null, true), credentials: true }));
const gl = rateLimit({ windowMs: 900000, max: 300 });
const al = rateLimit({ windowMs: 900000, max: 15 });
app.use('/api/', gl);
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true }));
app.use(morgan('combined'));
app.get('/health', (_r: any, res: any) => res.json({ status: 'ok' }));
app.get('/api/health', (_r: any, res: any) => res.json({ status: 'ok', version: '1.0.0' }));
app.use('/api/auth', al, authRouter);
app.use('/api/shop', shopRouter);
app.use('/api/customers', customersRouter);
app.use('/api/frames', framesRouter);
app.use('/api/lenses', lensesRouter);
app.use('/api/accessories', accessoriesRouter);
app.use('/api/orders', ordersRouter);
app.use('/api/lab-orders', labOrdersRouter);
app.use('/api/repairs', repairsRouter);
app.use('/api/prescriptions', prescriptionsRouter);
app.use('/api/staff', staffRouter);
app.use('/api/invoices', invoicesRouter);
app.use('/api/reports', reportsRouter);
app.use((_r: any, res: any) => res.status(404).json({ error: 'Not found' }));
app.use(errorHandler);
app.listen(PORT, '0.0.0.0', () => console.log('LensFlow running on ' + PORT));
export default app;
